# Generated by Django 2.1.5 on 2019-01-31 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_set', models.DateField(auto_now_add=True)),
                ('date_of_event', models.DateField()),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Schedule')),
            ],
        ),
    ]
