# Generated by Django 2.1.5 on 2019-01-24 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_adverts_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Teacher')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Classes')),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
